version: "3.8"

services:
  backend:
    build:
      context: ./HeavyEquipment-Be
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80;https://0.0.0.0:443
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=youtube
      - POSTGRES_HOST=db
      - POSTGRES_DB=equipmentdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - ./my-certificates/aspnetapp.pfx:/https/aspnetapp.pfx:ro
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    build:
      context: ./HeavyEquipment
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=https://heavy-equipment.my.id/api
    networks:
      - app-network

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=equipmentdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
